function result = run_optimization(material, params)

x0 = [0.15, 0.50, 0.005, 0.005, 180];

lb = [0.05, 0.10, 0.003, 0.003, 20];

ub = [0.30, 1.50, 0.03, 0.03, 200];

options = optimoptions(...
    'fmincon',...
    'Display','off',...
    'Algorithm','sqp');

[x_opt, ~] = fmincon(...
    @(x)objective_function(x, material, params),...
    x0,...
    [],[],[],[],...
    lb,...
    ub,...
    @(x)constraint_function(x, material, params),...
    options);

V_internal = internal_volume(...
    x_opt(1),...
    x_opt(2));

E_stored = energy_storage(...
    V_internal,...
    x_opt(5));

head_depth = x_opt(1) / 2;

Vmat = material_volume(...
    x_opt(1),...
    x_opt(2),...
    x_opt(3),...
    x_opt(4));

actual_mass = mass_calc(...
    Vmat,...
    material.rho);

result = table(...
    string(material.name),...
    material.rho,...
    material.S / 1e6,...
    x_opt(5),...
    V_internal,...
    E_stored,...
    x_opt(1),...
    x_opt(2),...
    head_depth,...
    x_opt(3),...
    x_opt(4),...
    actual_mass,...
    'VariableNames',...
    {'Material',...
     'Density',...
     'AllowableStressMPa',...
     'PressureBar',...
     'InternalVolume',...
     'StoredEnergyMJ',...
     'Radius',...
     'Length',...
     'HeadDepth',...
     'ShellThickness',...
     'HeadThickness',...
     'Mass'});

end